In [4]:
%pip install tensorflow


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
from tensorflow.keras.preprocessing.text import one_hot

In [37]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [38]:
voc_size = 10000  # Vocabulary size
### One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[858, 6956, 2196, 5280],
 [858, 6956, 2196, 5600],
 [858, 6917, 2196, 7068],
 [3532, 3611, 8002, 8527, 1027],
 [3532, 3611, 8002, 8527, 7544],
 [2635, 858, 6285, 2196, 4394],
 [9875, 9761, 5886, 8527]]

In [39]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [40]:
import numpy as np

In [41]:
sent_length = 8
embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  858 6956 2196 5280]
 [   0    0    0    0  858 6956 2196 5600]
 [   0    0    0    0  858 6917 2196 7068]
 [   0    0    0 3532 3611 8002 8527 1027]
 [   0    0    0 3532 3611 8002 8527 7544]
 [   0    0    0 2635  858 6285 2196 4394]
 [   0    0    0    0 9875 9761 5886 8527]]


In [42]:
## Feature representation
dim=10

In [43]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [44]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [45]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 94ms/step


array([[[ 0.01503868,  0.04434091,  0.02540716, -0.03190613,
          0.00091271, -0.03842136, -0.02296656,  0.0256413 ,
          0.02981205,  0.03806074],
        [ 0.01503868,  0.04434091,  0.02540716, -0.03190613,
          0.00091271, -0.03842136, -0.02296656,  0.0256413 ,
          0.02981205,  0.03806074],
        [ 0.01503868,  0.04434091,  0.02540716, -0.03190613,
          0.00091271, -0.03842136, -0.02296656,  0.0256413 ,
          0.02981205,  0.03806074],
        [ 0.01503868,  0.04434091,  0.02540716, -0.03190613,
          0.00091271, -0.03842136, -0.02296656,  0.0256413 ,
          0.02981205,  0.03806074],
        [-0.00166132,  0.01216171,  0.0265176 ,  0.01072343,
          0.02579821, -0.00379194, -0.00603002,  0.04957509,
          0.01404155, -0.00964554],
        [ 0.01899481,  0.02185552, -0.01761267, -0.01546614,
         -0.00145888, -0.03757588, -0.02155705,  0.04260572,
          0.0035944 ,  0.03662214],
        [-0.04335275, -0.03811715, -0.04812285, -0.0